### PR TITLE
[bugfix] Update windows buffer size

### PR DESCRIPTION
**Pull request by ken-schneider**
This addresses https://github.com/prometheus-community/pro-bing/issues/34

### CODE REVIEW

**Comment by olljanat** [comment]
@ken-schneider looks that your commits are missing signing (DCO). Guidance here is not too good so look example https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work what it means and how to do it.

**Comment by ken-schneider** [comment]
@olljanat thanks for pointing that out. Just amended the commit messages to include my sign off

**Comment by ken-schneider** [comment]
@olljanat @SuperQ @metalmatze would one of you mind having a look at this PR when you have a chance?

**Review by SuperQ — APPROVED** [review]
LGTM, Thanks

**Pull request merged**
