### PR TITLE
Return error instead of logging and continuing in runLoop()

### PR DESCRIPTION
**Pull request by floatingstatic**
I noticed when running pro-bing with a condition that triggers an error such as in a "no route to host" scenario that the run loop logs and continues the loop. This can be misleading to callers and should probably return an error. There are two sections in `runLoop()` with `FIXME` comments that explain this behavior. It would be more correct to return an error here.

This PR replaces `logger.Fatalf()` with a `return` of a wrapped error to remediate this. We use `%w` to wrap the error so callers can unwrap and inspect the errors with something like:

```
if err := pinger.RunWithContext(ctx); err != nil {
    if neterr, ok := errors.Unwrap(err).(*net.OpError); ok {
        // do something interesting here with the error
    }
}
```

### CODE REVIEW

**Comment by SuperQ** [comment]
""no route to host"" should not stop the loop.

**Comment by SuperQ** [comment]
> Lastly I apologize for the high number of PRs the past few days. My company has an internal application that uses a fork of go-ping/ping with internal patches from about 5 years ago. Given go-ping is no longer maintained we want to pull in pro-bing with a number of our internal patches upstreamed, at least the ones that make sense to share for general use. Thanks for your time reviewing these, I appreciate it.

More patches are great, thanks for contributing.

**Comment by floatingstatic** [comment]
>  Normal /usr/bin/ping also returns this error without stopping the loop

Right, that makes sense but i need a way to signal that this occurs in the ping response. Its obvious via stdout but not in the struct returned by a pinger. I need to be able to distinguish that 100% packet loss was due to some underlying condition reported by linux and not a path problem. Are you open to adding a boolean to selectively enable returning an error? I'll submit another commit that does this and you can let me know what you think of the implementation. Thanks!

**Comment by SuperQ** [comment]
Sounds like we need another packet handler function registry. Something like:

```go
if handler := p.OnPacketError; handler != nil {
	handler()
}
```

**Comment by floatingstatic** [comment]
I did this: https://github.com/prometheus-community/pro-bing/pull/40/commits/7268dfe273a5496cd328971cb8ebdbd75a7ec667

... but seeing your latest comment perhaps that is a better approach. Happy to go that route if its preferable.

**Comment by SuperQ** [comment]
I need to think about this, and how other error cases are handled.

**Comment by floatingstatic** [comment]
One brief thought, say we add something like this to the pinger:

```
OnPacketError func(*Packet, error)
```

One problem with this is it really only works for sending packets as we do not have packet info on the receiving side if we hit an error after `icmp.ParseMessage()` (for example). 

We could also do this to make it more generic to both sending and receiving:

```
OnPacketError func(error)
```

but then we miss out on the packet details in the case where we have that info.

Maybe a handler for sending and another for receiving makes more sense?

```
OnSendError func(*Packet, error)
OnReceiveError func(error)
```

For my use case, in either one of these functions I could call `pinger.Stop()` in a closure when i hit an error which meets my needs.

**Comment by floatingstatic** [comment]
Proposing #44 as an alternative to this PR based on comments from recent discussion

**Comment by floatingstatic** [comment]
Closing in favor of #44

**Pull request closed without merging**
